name: CI

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  get-examples:
    name: Get examples
    runs-on: ubuntu-latest
    timeout-minutes: 2

    permissions:
      contents: read

    outputs:
      names: ${{ steps.find.outputs.names }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - id: find
        working-directory: examples
        # produces the list of folder inside examples without leading `./` and trailing `/`:
        # ```text
        # base
        # react-trans-component-type-safe
        # ...
        # ```
        #
        # after, using `jq` the output is converted into a JSON array:
        # ```json
        # ["base","react-trans-component-type-safe","..."]
        # ```
        #
        # and added to `$GITHUB_OUTPUT` env variable:
        run: |
          NAMES=$(find . -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)
          echo "$NAMES" | jq -R -s -c 'split("\n")[:-1]'
          echo "names=$(echo "$NAMES" | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  test:
    name: Test "${{ matrix.example-name }}" (Node ${{ matrix.node-version }} / ${{ matrix.os }})

    permissions:
      contents: read

    timeout-minutes: 5

    runs-on: ${{ matrix.os }}

    needs:
      - get-examples

    strategy:
      matrix:
        example-name: ${{ fromJson(needs.get-examples.outputs.names) }}
        node-version:
          - 24
        os:
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Run build
      #   run: pnpm run build

      - name: Run tests
        run: pnpm --filter=${{ matrix.example-name }} run typecheck
